version: "3.4"
services:
  db:
    image: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 582676da
      MYSQL_DATABASE: niv
      MYSQL_USER: danilo
      MYSQL_PASSWORD: 582676da
  web:
    image: php:7.2-apache
    depends_on:
      - db
    volumes:
      - "./html:/var/www/html"
    ports:
      - "8080:80"
    links:
      - db
    restart: always